# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mivONe1JzS1cthywElvtZZamHfz2mSAL

#Assignment 1

#que1 Find out all the types of error that we have encountered in our lecture and why? Also include the examples.
"""

#Erro1 we need to use triple quotes while putting string values in different line
print("a
b
c")

#error 2 we use quote for string value in quote
print("my name is "akshay" ")

#error 3 we use special caharcter in variable(^ % $ ! @ # ^ & * ( ))
two* = 2
a#=34

#error4 we try add string and int value
"a"+1

#error5 we use keywords as avraiable
print="akshay"
print("akshay")

type(print)

#error 6 we use int value directly with input function which always gives string value
date_of_birth=input("date_of_birth:")
age =2022-date_of_birth

# error 7 we put float values while input in int value
a=float(input("a:"))
b=int(input("b:"))

#error 8 we try to convert string into integer
# String to integer
A = "34.55" #float value #value in A have to be int, even if it is string type
print(f"data type before: {type(A)}, value of A: {A}")
A = int(A) # trying to convert into integer
print(f"data type after: {type(A)}, value of A: {A}")

#error 9  while assigning function we give more values
def sum_of_values(x, y):
  print(x+y)

sum_of_values(22.2, 33, 444)

type(A)





"""#que2
#Take input A and B and print their sum, mul, div, square of the nos.
"""

a=int(input("enter ur num a:"))
b=int(input("enter ur num b:"))
print(f"sum of a and b:{a+b}")
print(f"sub of a and b:{a-b}")
print(f"mul of a and b:{a*b}")
print(f"Div of a and b:{a/b}")
print(f"square of a and b:{a**2},{b**2}")

"""#que3 How many reserve keywords are there in python and why we should not use them as a variable name."""

#there are 33 reserved keys.
print("""Reserved keywords are as follows:
False,	def	,if	,raise
None,	del,	import,	return
True,	elif,	in,	try
and,	else,	is,	while
as	,except,	lambda,	with
assert,	finally	,nonlocal,	yield
break,	for,	not	
class,	from,	or	
continue,	global,	pass""")
#we shouldn't use them as variable bcoz they define syntax,structure and function in python and are case sensitive



"""#que4 Create email ids with the user inputs. in the following format - lastname.firstname@gmail.com

"""

firstName, lastname = "Sunny", "Chandra"
print(f"{lastname}.{firstName}@gmail.com")

"""#que5Try to print the following lines -
##Hi I'm Sunny
##My address is 22\3
##I earn 20$ daily.
"""

print("Hi i'm Sunny")
print(f"My address is 22\\3")
print("I earn 20$ daily")

"""#que6 Take user input (name, address, date of birth etc) to fill a form for your college and print their email IDs

"""

name = input("Name: ") 
address = input("address: ")
date_of_birth = input("date_of_birth: ")
print(f"""
My name is: {name}
address: {address}
date of birth is:{date_of_birth}
""")

"""#que7 Convert the following -
##"22.4" into integer
##"22" into complex no.
"""

A=22.4
print(f"data type before:{type(A)},value of A:{A}")
A=int(A)
print(f"data type after:{type(A)},value of A:{A}")

B=22
print(f"data type before:{type(B)},value of B:{B}")
B=complex(B)
print(f"data type after:{type(B)},value of B:{B}")

